/*
MACPWDPWN (Mac Password Pwn) Account Unlocking Tool
For Mojave and above.

Copyright (C) techspider 2019. All rights reserved.
*/

#define APP_LOGO "                                       .___                    \n  _____ _____    ____ ________  _  ____| _/_______  _  ______  \n /     \\\\__  \\ _/ ___\\\\____ \\ \\/ \\/ / __ |\\____ \\ \\/ \\/ /    \\ \n|  Y Y  \\/ __ \\\\  \\___|  |_> >     / /_/ ||  |_> >     /   |  \\\n|__|_|  (____  /\\___  >   __/ \\/\\_/\\____ ||   __/ \\/\\_/|___|  /\n      \\/     \\/     \\/|__|              \\/|__|              \\/ \n"
#define SHADOW_HASH_DATA_UNLOCK "YnBsaXN0MDDSAQIDCl8QHlNSUC1SRkM1MDU0LTQwOTYtU0hBNTEyLVBCS0RGMl8QFFNBTFRFRC1TSEE1MTItUEJLREYy0wQFBgcICVh2ZXJpZmllclRzYWx0Wml0ZXJhdGlvbnNPEQIAIC5DcM0gFwwJgFKDpreW3wIbsH19H4aYnsNpAhyuJSFmOmaxK/WZxvVk+vDQu4SXgf/V5vstxRDvE3c4fGBKw3nUlqvq7dmh6d6HeuHwSn61A35s54flSxLZHaBT6dCVtzihnGcLtnzKMLeorBZvs8DDeZWoSoN8IbMg2GyR5+dia6gHD0BjAElRlW/3ua0YSU+WWBQ3KpoaoL2Onu2SnWGhqOCdVdzT7mgvvVxWX8+TS/J2bAaow5/L+g8UHjfvZm52EmjDAD4FaWbU04pmtuLLjnjL8qkJbGr9p5ySWXD+lDhYsUpTujD3ZS0qVavVQGJOd7fdIGPlcgZD1++bdWVC/lZnt6R6J32NhJIuCF2ZCd9O1RMqtIIsQdU1fdfW+UB4fi8wboBJGa7N+xuxiWtJjIPaau42GQglqX28RNmJbCcEbP+36X1iYU43COMD3ewPOz0mEF7OzDg0KuyxM8RL9+Kgt62Kfr4edk0g5oS+W1i2yfA8i3jMwHPhP+M18wpPtNRS+/fI+wJrzsExMzNzLtDEHSC42xpteIsHTDS8o2UGtAp/dtbbHgwsSo5ydiq5AZtxhSKLEUtnF3c1zZjEDm/clHGaHzc1PkSskRNaKwSCnrYFI/AP2VTChoNqEx2MGby3DNISqxV0C/JfAEj6fVFayCpu9WMy4k5Gl+hPECBzdLDjMwXrul5rsM0HzYwV8dhjfesDRcvevXYJQOJRwhHBYNMLBQYMDQ5XZW50cm9weU8QgIPpxn0yBKbKwdXs8X7QDyJg1xLtXSp0MgKpGxx9fLdth5ZP5tWcF36xZvzjXKqitrUTHt0LJJyujoK0gWQWi2diUwA2GJ+7Fl0rA9U0N1/OxhXd++2H+To301qkxrPsCYQR8Lj9GVteWjmwMP9erqTdi8KJ84XjVO7JlB64XqncTxAgL0/uvrOA5xxDzx1JIxgD3MVLtPkmyibWVKcGCQIzn7QRrNcACAANAC4ARQBMAFUAWgBlAmkCjAKPApYCngMhA0QAAAAAAAACAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAADRw==" //Default pwd 12345
